"""empty message

Revision ID: 7ef542144c88
Revises: 0074d7b73a51
Create Date: 2024-04-29 09:23:19.429238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72ef542144c88'
down_revision: Union[str, None] = 'e4b7e8c165c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_games',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('bet', sa.Float(), nullable=False),
    sa.Column('opponents', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'user_id', 'game_id'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_games')
    op.drop_table('games')
    # ### end Alembic commands ###
